name: Android CI

on:
  #push:
  #branches:
  # - '*'
  #- main
  # - 'feature/**'
  # - 'bugfix/**'
  # - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build dev flavor APK
        run: |
          echo "Building dev flavor..."
          ./gradlew assembleDevDebug --no-daemon --parallel --build-cache

      - name: Run Unit Tests
        run: |
          echo "Running unit tests..."
          ./gradlew test --no-daemon --build-cache

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-dev-debug.apk
          path: app/build/outputs/apk/dev/debug/*.apk
