name: Android CI

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Environment flavor to build (e.g., dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Run Android Lint
        run: ./gradlew lint${{ github.event.inputs.flavor }}Debug

      - name: Upload Lint HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: lint-report-${{ github.event.inputs.flavor }}
         path: app/build/reports/lint-results-${{ github.event.inputs.flavor }}Debug.html

      - name: Build selected flavor
        run: |
          echo "Building flavor: ${{ github.event.inputs.flavor }}Debug"
          ./gradlew assemble${{ github.event.inputs.flavor }}Debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.event.inputs.flavor }}-debug.apk
          path: app/build/outputs/apk/${{ github.event.inputs.flavor }}/debug/*.apk
